const ALERT_LEVELS = {
    UNHEALTHY_FOR_SENSITIVE_GROUPS: "UNHEALTHY_FOR_SENSITIVE_GROUPS",
    UNHEALTHY: "UNHEALTHY",
    VERY_UNHEALTHY: "VERY_UNHEALTHY",
    HAZARDOUS: "HAZARDOUS",
}

module.exports = { ALERT_LEVELS }