const AIR_QUALITY_CATEGORIES = {
    GOOD: "GOOD",
    MODERATE: "MODERATE",
    UNHEALTHY_FOR_SENSITIVE_GROUPS: "UNHEALTHY_FOR_SENSITIVE_GROUPS",
    UNHEALTHY: "UNHEALTHY",
    VERY_UNHEALTHY: "VERY_UNHEALTHY",
    HAZARDOUS: "HAZARDOUS",
    UNDEFINED: "UNDEFINED",
}

module.exports = {
    AIR_QUALITY_CATEGORIES
}