const PM10_QUALITY_LEVELS = {
    GOOD: 54,
    MODERATE: 154,
    UNHEALTHY_FOR_SENSITIVE_GROUPS: 254,
    UNHEALTHY: 354,
    VERY_UNHEALTHY: 424,
    HAZARDOUS: 600,
}

module.exports = {
    PM10_QUALITY_LEVELS
}