const VOC_QUALITY_LEVELS = {
    GOOD: 15,
    MODERATE: 25,
    UNHEALTHY_FOR_SENSITIVE_GROUPS: 50,
    UNHEALTHY: 75,
    VERY_UNHEALTHY: 100,
    HAZARDOUS: 150,
}

module.exports = {
    VOC_QUALITY_LEVELS
}