const SensorsActionTypes = {
    GET_MONTHLY_SENSOR_DATA_START: "GET_MONTHLY_SENSOR_DATA_START",
    GET_MONTHLY_SENSOR_DATA_SUCCESS: "GET_MONTHLY_SENSOR_DATA_SUCCESS",
    GET_MONTHLY_SENSOR_DATA_FAILURE: "GET_MONTHLY_SENSOR_DATA_FAILURE",    
   
    GET_WEEKLY_SENSOR_DATA_START: "GET_WEEKLY_SENSOR_DATA_START",
    GET_WEEKLY_SENSOR_DATA_SUCCESS: "GET_WEEKLY_SENSOR_DATA_SUCCESS",
    GET_WEEKLY_SENSOR_DATA_FAILURE: "GET_WEEKLY_SENSOR_DATA_FAILURE",
    
    GET_DAILY_SENSOR_DATA_START: "GET_DAILY_SENSOR_DATA_START",
    GET_DAILY_SENSOR_DATA_SUCCESS: "GET_DAILY_SENSOR_DATA_SUCCESS",
    GET_DAILY_SENSOR_DATA_FAILURE: "GET_DAILY_SENSOR_DATA_FAILURE",
    
    GET_LAST_SENSOR_DATA_START: "GET_LAST_SENSOR_DATA_START",
    GET_LAST_SENSOR_DATA_SUCCESS: "GET_LAST_SENSOR_DATA_SUCCESS",
    GET_LAST_SENSOR_DATA_FAILURE: "GET_LAST_SENSOR_DATA_FAILURE",

}

export default SensorsActionTypes;


