const PhoneActionTypes = {
    REGISTER_PHONE_START: "REGISTER_PHONE_START",
    REGISTER_PHONE_FAILED: "REGISTER_PHONE_FAILED",
    REGISTER_PHONE_SUCCESS: "REGISTER_PHONE_SUCCESS",
    VERIFY_PHONE_START: "VERIFY_PHONE_START",
    VERIFY_PHONE_FAILED: "VERIFY_PHONE_FAILED",
    VERIFY_PHONE_SUCCESS: "VERIFY_PHONE_SUCCESS",
}

export default PhoneActionTypes;


