const ALERT_LEVELS = {
    GOOD: "GOOD",
    MODERATE: "MODERATE",
    UNHEALTHY_FOR_SENSITIVE_GROUPS: "UNHEALTHY_FOR_SENSITIVE_GROUPS",
    UNHEALTHY: "UNHEALTHY",
    VERY_UNHEALTHY: "VERY_UNHEALTHY",
    HAZARDOUS: "HAZARDOUS",
}

export default ALERT_LEVELS;